/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.okhttp;

import android.os.Build;
import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.TiFileProxy;
import org.appcelerator.titanium.io.TiBaseFile;
import org.appcelerator.titanium.io.TiResourceFile;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.util.TiMimeTypeHelper;
import org.appcelerator.titanium.util.TiPlatformHelper;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.SocketTimeoutException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.Objects;

import okhttp3.Cache;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.ConnectionPool;
import okhttp3.Headers;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import okio.Buffer;
import okio.BufferedSink;
import okio.BufferedSource;
import okio.Okio;
import okio.Sink;
import okio.Source;
import okio.Timeout;


@Kroll.module(name = "TiOkhttp", id = "ti.okhttp")
public class TiOkhttpModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiOkhttpModule";
    private static final boolean DBG = TiConfig.LOGD;
    private static final String TITANIUM_USER_AGENT = "Titanium SDK/" + TiApplication.getInstance().getTiBuildVersion() + " (" + Build.MODEL + "; Android API Level: " + Build.VERSION.SDK_INT + "; " + TiPlatformHelper.getInstance().getLocale() + ";)";
    
    // Connection Pool settings
    private static final int DEFAULT_KEEP_ALIVE_DURATION = 15000; // ms
    private static final int DEFAULT_MAX_IDLE_CONNECTIONS = 1;
    private static final String DEFAULT_CONNECTION_ID = "default";
    
    private final OkHttpClient client = createDefaultClient();
    private final ConnectionPool defaultConnectionPool = createDefaultConnectionPool();

    private static OkHttpClient createDefaultClient() {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        // Default timeouts
        builder.connectTimeout(30, TimeUnit.SECONDS);
        builder.readTimeout(30, TimeUnit.SECONDS);
        builder.writeTimeout(30, TimeUnit.SECONDS);
        return builder.build();
    }

    private static ConnectionPool createDefaultConnectionPool() {
        return new ConnectionPool(DEFAULT_MAX_IDLE_CONNECTIONS, DEFAULT_KEEP_ALIVE_DURATION, TimeUnit.MILLISECONDS);
    }

    /**
     * Get or create a ConnectionPool for the given connection ID
     */
    private ConnectionPool getConnectionPool(String connectionId, int maxIdleConnections, long keepAliveDuration) {
        // For simplicity, we create a new pool per request
        // In a real implementation, you would cache pools by connectionId
        return new ConnectionPool(maxIdleConnections, keepAliveDuration, TimeUnit.MILLISECONDS);
    }

    public TiOkhttpModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
        // Module initialization
    }

    /**
     * Parse request headers and configuration from KrollDict
     */
    private Request parseRequest(@Kroll.argument(optional = true) @NonNull KrollDict data, @Nullable RequestBody body, String method) {
        Objects.requireNonNull(data, "data cannot be null");

        String url = data.getString("url");
        if (url == null || url.trim().isEmpty()) {
            Log.e(LCAT, "URL is required and cannot be empty");
            throw new IllegalArgumentException("URL is required");
        }

        Request.Builder requestBuilder = new Request.Builder()
                .header("User-Agent", TITANIUM_USER_AGENT)
                .url(url);

        // Parse host override (for custom hosts)
        if (data.containsKeyAndNotNull("host")) {
            String host = data.getString("host");
            if (host != null && !host.isEmpty()) {
                // OkHttp doesn't support custom hosts directly in Request.Builder
                // The host property is documented but the actual URL should contain the host
                Log.w(LCAT, "Host property is set but URL already contains host information");
            }
        }

        // Parse headers
        if (data.containsKeyAndNotNull("header")) {
            Object headerObj = data.get("header");
            if (headerObj instanceof Map) {
                @SuppressWarnings("unchecked")
                Map<String, String> headerData = (Map<String, String>) headerObj;
                headerData.forEach((key, value) -> {
                    if (key != null && value != null) {
                        requestBuilder.removeHeader(key);
                        requestBuilder.addHeader(key, value);
                    }
                });
            }
        }

        KrollFunction clbSuccess = null;
        KrollFunction clbError = null;
        if (data.containsKeyAndNotNull("success")) {
            Object successObj = data.get("success");
            if (successObj instanceof KrollFunction) {
                clbSuccess = (KrollFunction) successObj;
            }
        }
        if (data.containsKeyAndNotNull("error")) {
            Object errorObj = data.get("error");
            if (errorObj instanceof KrollFunction) {
                clbError = (KrollFunction) errorObj;
            }
        }
        RequestContext ctx = new RequestContext(clbSuccess, clbError);

        if (body != null) {
            if ("DELETE".equals(method)) {
                requestBuilder.delete(body);
            } else {
                requestBuilder.post(body);
            }
        }

        return requestBuilder.tag(ctx).build();
    }

    /**
     * Parse client configuration (timeouts, caching, connection pooling) from KrollDict
     */
    private OkHttpClient.Builder parseData(@NonNull KrollDict data) {
        OkHttpClient.Builder clientBuilder = client.newBuilder();

        // Timeouts
        if (data.containsKeyAndNotNull("connectTimeout")) {
            clientBuilder.connectTimeout(data.getInt("connectTimeout"), TimeUnit.MILLISECONDS);
        }
        if (data.containsKeyAndNotNull("readTimeout")) {
            clientBuilder.readTimeout(data.getInt("readTimeout"), TimeUnit.MILLISECONDS);
        }
        if (data.containsKeyAndNotNull("writeTimeout")) {
            clientBuilder.writeTimeout(data.getInt("writeTimeout"), TimeUnit.MILLISECONDS);
        }

        // Connection Pooling
        int maxIdleConnections = DEFAULT_MAX_IDLE_CONNECTIONS;
        long keepAliveDuration = DEFAULT_KEEP_ALIVE_DURATION;
        String connectionId = DEFAULT_CONNECTION_ID;

        if (data.containsKeyAndNotNull("maxIdleConnections")) {
            maxIdleConnections = data.getInt("maxIdleConnections");
        }
        if (data.containsKeyAndNotNull("keepAliveDuration")) {
            keepAliveDuration = data.getInt("keepAliveDuration");
        }
        if (data.containsKeyAndNotNull("connectionId")) {
            connectionId = data.getString("connectionId");
        }

        // Use a custom connection pool per request for the given connectionId
        // In a full implementation, you would cache pools by connectionId
        ConnectionPool connectionPool = getConnectionPool(connectionId, maxIdleConnections, keepAliveDuration);
        clientBuilder.connectionPool(connectionPool);

        // Caching
        if (data.containsKeyAndNotNull("caching") && data.getBoolean("caching")) {
            int cacheSize = 10;
            if (data.containsKeyAndNotNull("cacheSize")) {
                cacheSize = data.getInt("cacheSize");
            }
            File file = TiApplication.getInstance().getTiTempDir().getAbsoluteFile();
            if (file != null && file.exists() && file.isDirectory()) {
                try {
                    clientBuilder.cache(CacheResponse(file, cacheSize));
                } catch (Exception exception) {
                    Log.e(LCAT, "Failed to configure cache: " + exception.getMessage(), exception);
                }
            }
        } else {
            // Disable cache by default
            clientBuilder.cache(null);
        }
        return clientBuilder;
    }

    // Methods
    @Kroll.method
    public void get(@Kroll.argument(optional = true) @NonNull KrollDict data) {
        Objects.requireNonNull(data, "data cannot be null");

        if (!data.containsKeyAndNotNull("url")) {
            Log.e(LCAT, "Please set an URL");
            return;
        }

        OkHttpClient.Builder clientBuilder = parseData(data);
        Request request;
        try {
            request = parseRequest(data, null, "GET");
        } catch (IllegalArgumentException e) {
            Log.e(LCAT, e.getMessage());
            return;
        }

        final RequestContext ctx = (RequestContext) request.tag();

        // Progress Tracking for download
        if (data.containsKeyAndNotNull("trackProgress") && data.getBoolean("trackProgress")) {
            final ProgressListener progressListener = new ProgressListener() {
                @Override
                public void onUploadProgress(long bytesWritten, long contentLength, boolean done) {
                    // Not used for GET requests
                }

                @Override
                public void onDownloadProgress(long bytesRead, long contentLength, boolean done) {
                    if (contentLength > 0) {
                        KrollDict progress = new KrollDict();
                        progress.put("url", data.getString("url"));
                        progress.put("type", "download");
                        progress.put("bytesWritten", bytesRead);
                        progress.put("contentLength", contentLength);
                        progress.put("progress", (int) ((bytesRead * 100.0) / contentLength));
                        progress.put("transferred", bytesRead);
                        progress.put("total", contentLength);
                        runOnUiThread(() -> {
                            fireEvent("downloadProgress", progress);
                            if (ctx != null && ctx.success != null) {
                                ctx.success.callAsync(getKrollObject(), progress);
                            }
                        });
                    }
                }
            };
            Log.d(LCAT, "HTTP GET request with progress tracking to: " + data.getString("url"));
            clientBuilder.build().newCall(request).enqueue(new Callback() {
                @Override
                public void onFailure(@NonNull Call call, @NonNull IOException e) {
                    createErrorEvent(call, e);
                }

                @Override
                public void onResponse(@NonNull Call call, @NonNull Response response) {
                    try (ResponseBody responseBody = response.body()) {
                        ProgressResponseBody wrappedBody = new ProgressResponseBody(responseBody, progressListener);
                        if (response.isSuccessful()) {
                            createReturnEvent(call, response.headers(), wrappedBody, response, data);
                        } else {
                            handleErrorResponse(call, response, data);
                        }
                    } catch (Exception exception) {
                        Log.e(LCAT, "Response processing error: " + exception.getMessage(), exception);
                        createErrorEvent(call, new IOException(exception));
                    }
                }
            });
        } else {
            Log.d(LCAT, "HTTP GET request to: " + data.getString("url"));
            clientBuilder.build().newCall(request).enqueue(new Callback() {
                @Override
                public void onFailure(@NonNull Call call, @NonNull IOException e) {
                    createErrorEvent(call, e);
                }

                @Override
                public void onResponse(@NonNull Call call, @NonNull Response response) {
                    try (ResponseBody responseBody = response.body()) {
                        if (response.isSuccessful()) {
                            createReturnEvent(call, response.headers(), responseBody, response, data);
                        } else {
                            handleErrorResponse(call, response, data);
                        }
                    } catch (Exception exception) {
                        Log.e(LCAT, "Response processing error: " + exception.getMessage(), exception);
                        createErrorEvent(call, new IOException(exception));
                    }
                }
            });
        }
    }

    private Cache CacheResponse(File cacheDirectory, int value) throws Exception {
        int cacheSize = value * 1024 * 1024; // MiB
        return new Cache(cacheDirectory, cacheSize);
    }

    private void createErrorEvent(@NonNull Call call, @NonNull IOException e) {
        KrollDict kd = new KrollDict();
        kd.put("timeout", e instanceof SocketTimeoutException);
        kd.put("message", e.getMessage() != null ? e.getMessage() : e.toString());
        fireEvent("error", kd);

        RequestContext ctx = (RequestContext) call.request().tag();
        if (ctx != null && ctx.error != null) {
            ctx.error.callAsync(getKrollObject(), kd);
        }
    }

    private void handleErrorResponse(@NonNull Call call, @NonNull Response response, @NonNull KrollDict data) {
        RequestContext ctx = (RequestContext) call.request().tag();
        if (ctx != null && ctx.error != null) {
            KrollDict kd = new KrollDict();
            kd.put("url", data.getString("url"));
            kd.put("statusCode", response.code());
            kd.put("statusMessage", response.message());
            try {
                kd.put("body", response.body() != null ? response.body().string() : "");
            } catch (IOException e) {
                kd.put("body", "");
            }
            ctx.error.callAsync(getKrollObject(), kd);
        }
        fireEvent("error", new KrollDict());
    }

    private void createReturnEvent(@NonNull Call call, @NonNull Headers header, @NonNull ResponseBody body, @NonNull Response response, @NonNull KrollDict data) {
        KrollDict output = new KrollDict();
        output.put("header", header.toString());
        try {
            output.put("body", body.string());
        } catch (Exception exception) {
            output.put("body", "");
        }

        boolean isCached = response.cacheResponse() != null;
        String networkResponse = response.networkResponse() != null ? response.networkResponse().toString() : "";

        output.put("url", data.getString("url"));
        output.put("data", data.getKrollDict("data"));
        output.put("cached", isCached);
        output.put("networkResponse", networkResponse);
        output.put("protocol", response.protocol().toString());
        output.put("statusCode", response.code());
        output.put("statusMessage", response.message());

        RequestContext ctx = (RequestContext) call.request().tag();
        if (ctx != null && ctx.success != null) {
            ctx.success.callAsync(getKrollObject(), output);
        }
        fireEvent("data", output);
    }

    @Kroll.method
    public void post(@Kroll.argument(optional = true) @NonNull KrollDict data) {
        Objects.requireNonNull(data, "data cannot be null");

        if (!data.containsKeyAndNotNull("url")) {
            Log.e(LCAT, "Please set an URL");
            return;
        }

        OkHttpClient.Builder clientBuilder = parseData(data);

        RequestBody body;
        try {
            body = createRequestBody(data);
        } catch (Exception e) {
            Log.e(LCAT, "Failed to create request body: " + e.getMessage(), e);
            createErrorEvent(null, new IOException(e));
            return;
        }

        // Progress Tracking for upload
        if (data.containsKeyAndNotNull("trackProgress") && data.getBoolean("trackProgress")) {
            final ProgressListener progressListener = new ProgressListener() {
                @Override
                public void onUploadProgress(long bytesWritten, long contentLength, boolean done) {
                    if (contentLength > 0) {
                        KrollDict progress = new KrollDict();
                        progress.put("url", data.getString("url"));
                        progress.put("type", "upload");
                        progress.put("bytesWritten", bytesWritten);
                        progress.put("contentLength", contentLength);
                        progress.put("progress", (int) ((bytesWritten * 100.0) / contentLength));
                        progress.put("transferred", bytesWritten);
                        progress.put("total", contentLength);
                        runOnUiThread(() -> {
                            fireEvent("uploadProgress", progress);
                            // Note: No success callback for upload progress
                        });
                    }
                }

                @Override
                public void onDownloadProgress(long bytesRead, long contentLength, boolean done) {
                    // Not used for upload progress
                }
            };
            body = new ProgressRequestBody(body, progressListener);
        }

        Request request;
        try {
            request = parseRequest(data, body, "POST");
        } catch (IllegalArgumentException e) {
            Log.e(LCAT, e.getMessage());
            return;
        }

        Log.d(LCAT, "HTTP POST request to: " + data.getString("url"));
        clientBuilder.build().newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                createErrorEvent(call, e);
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        createReturnEvent(call, response.headers(), responseBody, response, data);
                    } else {
                        handleErrorResponse(call, response, data);
                    }
                } catch (Exception exception) {
                    Log.e(LCAT, "Response processing error: " + exception.getMessage(), exception);
                    createErrorEvent(call, new IOException(exception));
                }
            }
        });
    }

    @Kroll.method
    public void deleteRoute(@Kroll.argument(optional = true) @NonNull KrollDict data) {
        Objects.requireNonNull(data, "data cannot be null");

        if (!data.containsKeyAndNotNull("url")) {
            Log.e(LCAT, "Please set an URL");
            return;
        }

        OkHttpClient.Builder clientBuilder = parseData(data);

        RequestBody body;
        try {
            body = createRequestBody(data);
        } catch (Exception e) {
            Log.e(LCAT, "Failed to create request body: " + e.getMessage(), e);
            createErrorEvent(null, new IOException(e));
            return;
        }

        Request request;
        try {
            request = parseRequest(data, body, "DELETE");
        } catch (IllegalArgumentException e) {
            Log.e(LCAT, e.getMessage());
            return;
        }

        Log.d(LCAT, "HTTP DELETE request to: " + data.getString("url"));
        clientBuilder.build().newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                createErrorEvent(call, e);
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        createReturnEvent(call, response.headers(), responseBody, response, data);
                    } else {
                        handleErrorResponse(call, response, data);
                    }
                } catch (Exception exception) {
                    Log.e(LCAT, "Response processing error: " + exception.getMessage(), exception);
                    createErrorEvent(call, new IOException(exception));
                }
            }
        });
    }

    /**
     * Create RequestBody from data (JSON or Multipart)
     */
    @NonNull
    private RequestBody createRequestBody(@NonNull KrollDict data) throws Exception {
        Object dataObj = data.get("data");

        if (dataObj instanceof HashMap) {
            @SuppressWarnings("unchecked")
            HashMap<String, Object> localData = (HashMap<String, Object>) dataObj;

            if (hasFileOrBlob(localData)) {
                return createMultipartBody(localData);
            } else {
                return createJsonRequestBody(localData);
            }
        } else if (dataObj instanceof String) {
            MediaType JSON = MediaType.parse("application/json");
            return RequestBody.create((String) dataObj, JSON);
        }

        // Empty body for POST without data or unsupported types
        return RequestBody.create(new byte[0], MediaType.parse("application/json"));
    }

    /**
     * Check if data contains file or blob objects (requires multipart)
     */
    private boolean hasFileOrBlob(@NonNull HashMap<String, Object> localData) {
        for (Object value : localData.values()) {
            if (value == null) continue;

            if (value instanceof TiFileProxy) {
                return true;
            }
            if (value instanceof TiBaseFile || value instanceof TiBlob) {
                return true;
            }
        }
        return false;
    }

    /**
     * Create MultipartBody for file uploads
     */
    @NonNull
    private RequestBody createMultipartBody(@NonNull HashMap<String, Object> localData) throws IOException {
        MultipartBody.Builder multipartBody = new MultipartBody.Builder();
        multipartBody.setType(MultipartBody.FORM);

        for (Map.Entry<String, Object> entry : localData.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();

            if (value == null) continue;

            try {
                if (value instanceof TiFileProxy) {
                    value = ((TiFileProxy) value).getBaseFile();
                }

                if (value instanceof TiBaseFile && !(value instanceof TiResourceFile)) {
                    File file = ((TiBaseFile) value).getNativeFile();
                    if (file != null && file.exists()) {
                        MediaType mediaType = MediaType.parse(TiMimeTypeHelper.getMimeType(file.getAbsolutePath()));
                        multipartBody.addFormDataPart(key, file.getName(), RequestBody.create(file, mediaType));
                    }
                } else if (value instanceof TiBlob) {
                    TiBlob blob = (TiBlob) value;
                    String mimeType = blob.getMimeType();
                    File tempFile = File.createTempFile(
                            "tixhr",
                            "." + TiMimeTypeHelper.getFileExtensionFromMimeType(mimeType, "txt"),
                            TiApplication.getInstance().getTiTempDir());
                    createFileFromBlob(blob, tempFile);
                    MediaType mediaType = MediaType.parse(TiMimeTypeHelper.getMimeType(tempFile.getAbsolutePath()));
                    multipartBody.addFormDataPart(key, tempFile.getName(), RequestBody.create(tempFile, mediaType));
                } else if (value instanceof TiResourceFile) {
                    TiBlob blob = ((TiResourceFile) value).read();
                    String mimeType = blob.getMimeType();
                    File tempFile = File.createTempFile(
                            "tixhr",
                            "." + TiMimeTypeHelper.getFileExtensionFromMimeType(mimeType, "txt"),
                            TiApplication.getInstance().getTiTempDir());
                    createFileFromBlob(blob, tempFile);
                    MediaType mediaType = MediaType.parse(TiMimeTypeHelper.getMimeType(tempFile.getAbsolutePath()));
                    multipartBody.addFormDataPart(key, tempFile.getName(), RequestBody.create(tempFile, mediaType));
                } else {
                    // normal key/value
                    multipartBody.addFormDataPart(key, TiConvert.toString(value));
                }
            } catch (IOException e) {
                Log.e(LCAT, "Error adding part '" + key + "': " + e.getMessage(), e);
            }
        }

        return multipartBody.build();
    }

    /**
     * Create JSON RequestBody
     */
    @NonNull
    private RequestBody createJsonRequestBody(@Nullable HashMap<String, Object> localData) throws IOException {
        String postBody;
        if (localData != null && !localData.isEmpty()) {
            try {
                postBody = TiConvert.toJSON(localData).toString();
            } catch (Exception e) {
                postBody = "{}";
            }
        } else {
            postBody = "{}";
        }

        MediaType JSON = MediaType.parse("application/json");
        return RequestBody.create(postBody, JSON);
    }

    /**
     * Create file from TiBlob
     */
    private void createFileFromBlob(@NonNull TiBlob blob, @NonNull File file) throws IOException {
        try (BufferedInputStream bufferedInput = new BufferedInputStream(blob.getInputStream());
             BufferedOutputStream bufferedOutput = new BufferedOutputStream(new FileOutputStream(file))) {

            byte[] buffer = new byte[8192]; // 8KB buffer (more efficient than 8MB for typical files)
           int bytesRead;
            while ((bytesRead = bufferedInput.read(buffer)) != -1) {
                bufferedOutput.write(buffer, 0, bytesRead);
            }
            bufferedOutput.flush();
        }
    }

    // Progress Tracking Support
    // =========================

    /**
     * ProgressRequestBody for upload tracking
     */
    private static class ProgressRequestBody extends RequestBody {
        private final RequestBody delegate;
        private final ProgressListener progressListener;
        private long totalBytesWritten = 0L;
        private boolean completed = false;

        ProgressRequestBody(RequestBody delegate, ProgressListener progressListener) {
            this.delegate = delegate;
            this.progressListener = progressListener;
        }

        @Override
        public MediaType contentType() {
            return delegate.contentType();
        }

        @Override
        public long contentLength() throws IOException {
            return delegate.contentLength();
        }

        @Override
        public void writeTo(BufferedSink sink) throws IOException {
            Sink wrappingSink = new Sink() {
                @Override
                public void write(Buffer source, long byteCount) throws IOException {
                    sink.write(source, byteCount);
                    totalBytesWritten += byteCount;
                    long contentLength = contentLength();
                    progressListener.onUploadProgress(totalBytesWritten, contentLength, false);
                }

                @Override
                public void flush() throws IOException {
                    sink.flush();
                }

                @Override
                public void close() throws IOException {
                    sink.close();
                    if (!completed) {
                        completed = true;
                        long contentLength = contentLength();
                        progressListener.onUploadProgress(totalBytesWritten, contentLength, true);
                    }
                }

                @Override
                public Timeout timeout() {
                    return sink.timeout();
                }
            };

            BufferedSink bufferedSink = Okio.buffer(wrappingSink);
            delegate.writeTo(bufferedSink);
            bufferedSink.flush();
        }
    }

    /**
     * ProgressResponseBody for download tracking
     */
    private static class ProgressResponseBody extends ResponseBody {
        private final ResponseBody delegate;
        private final ProgressListener progressListener;
        private BufferedSource bufferedSource;

        ProgressResponseBody(ResponseBody delegate, ProgressListener progressListener) {
            this.delegate = delegate;
            this.progressListener = progressListener;
        }

        @Override
        public MediaType contentType() {
            return delegate.contentType();
        }

        @Override
        public long contentLength() {
            return delegate.contentLength();
        }

        @Override
        public BufferedSource source() {
            if (bufferedSource == null) {
                bufferedSource = Okio.buffer(source(delegate.source()));
            }
            return bufferedSource;
        }

        private Source source(Source source) {
            return new Source() {
                long totalBytesRead = 0L;

                @Override
                public long read(Buffer sink, long byteCount) throws IOException {
                    long bytesRead = source.read(sink, byteCount);
                    totalBytesRead += bytesRead != -1 ? bytesRead : 0;
                    long contentLength = delegate.contentLength();
                    progressListener.onDownloadProgress(totalBytesRead, contentLength, bytesRead == -1);
                    return bytesRead;
                }

                @Override
                public void close() throws IOException {
                    source.close();
                }

                @Override
                public Timeout timeout() {
                    return source.timeout();
                }
            };
        }
    }

    /**
     * ProgressListener interface for progress updates
     */
    private interface ProgressListener {
        void onUploadProgress(long bytesWritten, long contentLength, boolean done);
        void onDownloadProgress(long bytesRead, long contentLength, boolean done);
    }

    /**
     * Run code on the UI thread using Handler
     */
    private void runOnUiThread(Runnable runnable) {
        Handler handler = new Handler(Looper.getMainLooper());
        handler.post(runnable);
    }
}
